[[redirects]]
  from = "/*"
  to = "public/index.html"
  status = 200

[[redirects]]
  from = "/api/scan"
  to = "https://main--markshify.netlify.app/scan"
  status = 200

[build]
  publish = "public"
  command = "echo 'No build command, just publish the public folder.'"